version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: dima
      POSTGRES_PASSWORD: 658941
      POSTGRES_DB: fastAPI_hour
